### ISSUE TITLE
Documentation says CentOS is supported but the module says otherwise.

### ISSUE THREAD

**Issue by notjoe** [joshuabaird/puppet-ipaclient#29] opened 2015-04-05 14:29 UTC
Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Evaluation Error: Error while evaluating a Function Call, This module does not support operatingsystem CentOS at /etc/puppet/environments/production/modules/ipaclient/manifests/params.pp:73:7 on node

I am running CentOS 6.6.

**Comment by stbenjam** [comment] 2015-04-05 22:54
It should do, what's the output of `facter osfamily`?

**Comment by dotspec** [comment] 2015-06-23 22:42
I actually get the same error on Ubuntu and haven't figured out what's causing it to fall to the default.  Facter output is expected, if I can figure out what the cause is I'll follow up.

facter | grep operatingsystem
operatingsystem => Ubuntu
osfamily => Debian

**Comment by dotspec** [comment] 2015-06-23 22:57
I was able to track it down (after my stealth comment edit and stealth comment un-edit).  Here's the culprit: https://tickets.puppetlabs.com/browse/PUP-2373

Quoting every case of Debian and Redhat in both the params.pp and sudoers.pp fixed the issue for me.

**Comment by stbenjam** [comment] 2015-06-26 01:19
Fixed in https://github.com/stbenjam/puppet-ipaclient/pull/28

**Closed as completed by stbenjam** 2015-06-26 01:19 UTC
